# Generated by Django 6.0.6 on 2026-06-21 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Duplex', 'Duplex'), ('Bungalow', 'Bungalow'), ('Land', 'Land'), ('Commercial', 'Commercial'), ('Warehouse', 'Warehouse'), ('Office', 'Office')], max_length=50)),
                ('listing_type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Shortlet', 'Shortlet'), ('Lease', 'Lease')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location_state', models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja (FCT)'), ('Rivers', 'Rivers'), ('Oyo', 'Oyo'), ('Kano', 'Kano'), ('Enugu', 'Enugu'), ('Delta', 'Delta'), ('Anambra', 'Anambra'), ('Kaduna', 'Kaduna'), ('Cross River', 'Cross River'), ('Other', 'Other')], max_length=100)),
                ('location_area', models.CharField(max_length=200)),
                ('location_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amenities', models.TextField(default='[]')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('payment_terms', models.CharField(choices=[('full_upfront', 'Full Payment Upfront'), ('part_payment', 'Part Payment Allowed'), ('escrow', 'Escrow'), ('pod', 'Payment Upon Inspection'), ('negotiable', 'Negotiable')], default='full_upfront', max_length=30)),
                ('allows_part_payment', models.BooleanField(default=False)),
                ('minimum_deposit_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_diaspora_friendly', models.BooleanField(default=False)),
                ('is_direct_liquidation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
